// <auto-generated />
namespace s4t.Erp.Graos.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BoletimLoteRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BoletimLoteRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201803091154221_BoletimLoteRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
